category: Web
description: Octane Server is a web front end to Octane.
executables:
  octane-server:
    dependencies:
    - aeson
    - amazonka
    - amazonka-s3
    - base
    - http-types
    - lens
    - octane
    - text
    - wai
    - wai-extra
    - warp
    main: Main.hs
extra-source-files:
- CHANGELOG.markdown
- package.yaml
- README.markdown
- stack.yaml
ghc-options: -Wall
license: MIT
license-file: LICENSE.markdown
maintainer: Taylor Fausak
name: octane-server
synopsis: A web front end to Octane.
version: '0.1.0'
