allow-newer: true
extra-deps:
- convertible-1.1.1.0
- HDBC-2.4.0.1
- HDBC-sqlite3-2.3.3.1
packages:
- .
- location:
    commit: c5250d3ec6b2eb4ae413893e205fae2b356f4b1e
    git: git@github.com:tfausak/octane.git
  extra-dep: true
resolver: nightly-2016-06-12
